---
title: "Covid19 Analysis"
author: "Numrah Alauddin"
date: "12/10/2021"
output: word_document
---
```{r}
#Library Defined

knitr::opts_chunk$set(error = TRUE)
library(Hmisc)
library(factoextra)
library(dplyr)
```


```{r}
#File that have been called for the data

data <- read.csv("C:/Users/ARSALAN IQBAL/Downloads/COVID19_line_list_data.csv")
data <- select(data,-c(X.1:X.6))
data <- select(data,-c(X))
data_copied <- data
describe(data)
data_copied$death_dummy <- as.integer(data$death !=0)
data_copied <- select(data_copied,-c(2,9,10,11,12,13,18,19))
data_copied <- na.omit(data_copied)
summary(data_copied)
```

Comment:



```{r}
#Deaths of the patients

death_all = subset(data_copied,death_dummy == 1)
hist(death_all$age, col='maroon',main='Deaths Female Covid Effecties w.r.t Age',xlab="Age")
```

```{r}
#Gender wise Deaths (Male)

men <- subset(data_copied, gender == "male")
mendeath <- subset(men,death_dummy == 1)
hist(mendeath$age, col='brown',main='Deaths of Male Covid Effecties w.r.t Age',xlab="Age")
```
Comment:







```{R}
#Gender wise Deaths (Female)

women <- subset(data_copied, gender == "female")
womendeath <- subset(women,death_dummy == 1)
hist(womendeath$age, col='light blue',main='Deaths of Female Covid Effecties w.r.t Age',xlab="Age")
```
Comment:






```{R}
#Called Principle Component Analysis on our data

head(data_copied)
data_copiedpc <- data_copied[,c(7,8,9)]
pc.data <- princomp(data_copiedpc, cor = TRUE)
screeplot(pc.data,type="l", main="Screeplot for the Covid Data")
abline(1,0,col= 'red',lty=2)
```

Comment:


```{r}
#Regression and Data Validation

death_dummy <- as.integer(data$death !=0)
plot(data_copied$age,data_copied$death_dummy,main="Data Validation",xlab = "Age",ylab = "Probability")
```

Comment:


```{r}
#Clustering of Age, From Wuhan, Visiting Wuhan and Deaths

data_ultra <- select(data_copied,-c(1,2,3,4,5,6,10,11,12))
data_ultra <- na.omit(data_ultra)
km <- kmeans(data_ultra, centers = 5, nstart = 100)
fviz_cluster(km, data = data_ultra)
```

Comment:


